# ==============================================================================
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: wil-svc
  labels:
    app: wil
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30088
  selector:
    app: wil

---

# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-dp
  labels:
    app: wil
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wil
    spec:
      containers:
      - name: wil-ctn
        image: wil42/playground:v2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8888
  selector:
    matchLabels:
      app: wil
